admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

restaurante:
    resource: "@RestauranteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
